### PR TITLE
fix the bug

### LINKED ISSUE #105: Select and then de-select the user-cards in PickUserFragment will cause NullPointerException
???

### PR DESCRIPTION
**Pull request by yenanw**
it was caused by List<Integer> interpreting remove(Object o) as remove(int index),
goddamn method overload

fixes #105

### CODE REVIEW

File: app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java [hunk 1]
```diff
@@ -132,29 +132,33 @@ public PickUserViewHolder(@NonNull View itemView) {
...
             });
         }
 
+        private synchronized void updateSelection() {
+            if (isMultipleChoice) { // if checkbox
+                boolean isChecked = checkBox.isChecked();
+                if (isChecked) {
+                    // if the checkbox is already checked
+                    // remove the position from the posList
+                    selectedUserPosList.remove(Integer.valueOf(getAdapterPosition()));
```
Comment (Puh00) [inline app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java:146]: Interesting

**Review by Puh00 — APPROVED** [review]
